# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-24 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=100)),
                ('short_name', models.TextField()),
                ('exchange_rate', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
            options={
                'ordering': ('updated',),
            },
        ),
    ]
