# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-26 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencydata',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='currencydata',
            name='short_name',
            field=models.TextField(blank=True, default='', max_length=10),
        ),
    ]
